# This is a basic workflow to help you get started with Actions

name: CI Windows EXE Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    paths:
      - '**.py'

  pull_request:
    paths:
      - '**.py'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1


      
      # Set branch name
      - name: Set branch name
        run: |
          $branchName = $Env:GITHUB_REF -replace "refs/heads/", ""
          echo $branchName

      # Install all required dependencies and pyinstaller to package code
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      # Package script and move to root folder
      - name: Package Script to EXE
        run: |
          rm covid-vaccine-slot-booking.exe -ErrorAction Ignore
          cd src
          pyinstaller covid-vaccine-slot-booking.py

      # Copy library files
      - name: copy fonts folder
        uses: MadaraUchiha/copy-action@0.0.1
        with:
          source: libs\fonts
          target: dist\covid-vaccine-slot-booking\reportlab\
      - name: make the zip file of dist folder

      # Make zip file
        uses: papeloto/action-zip@v1
        with:
          files: dist/
          dest: windows-exe.zip

      # Remove not required files
      - name: Package Script to EXE
        run: |
          rm -r /build -ErrorAction Ignore

      # Commit and push EXE file to branch
      - name: Push EXE to branch
        run: |
          git add covid-vaccine-slot-booking.exe
          git commit -m "rebuilt via GitHub Actions"
          git push --force
